site_name: 'python-app'
site_description: 'Main documentation for the python-app'
repo_url: https://github.com/swas-kar/python-app
edit_uri: edit/main/docs

plugins:
  - techdocs-core

# For sidebar navigation on https://backstage.io/, see `microsite/sidebars.js`
nav:
  - Overview:
<<<<<<< HEAD
      - Getting Started: 'docs/index.md'
=======
      - Getting Started: 'docs/index.md'
>>>>>>> ea9c6e8 (Updates files)
