name: ci

on:
  push:
    paths:
      - 'src/**'
    branches:
      - main

jobs:
  docker:
    runs-on: self-hosted
    steps:
      -
        name: Shortening the commit id
        shell: bash
        run : |
          echo "COMMIT_ID=${GITHUB_SHA::6}" >> "$GITHUB_ENV"
          echo "branch=$(echo ${GITHUB_REF#refs/heads/})" >> "$GITHUB_ENV"
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: swaskar03/python-app:${{ env.COMMIT_ID }}